switch sourceCompat back to java 8
since I'm seeing weird errors in the pre-launch report.
(stuff like `java.lang.NoClassDefFoundError: j$.time.a    at j$.time.Instant.now`)
Not really sure why this is, but jvm compat is my first guess.